dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
# before_install:
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  # - npm i -g npm@^3
install:
  - cd webpack-vanilla && npm install && cd ..
script:
  - cd webpack-vanilla && npm run lint && cd ..
  - cd webpack-vanilla && npm run test && cd ..
  - cd webpack-vanilla && npm run build && cd ..
  # - cd webpack-vanilla && npm run test-once && cd ..
  # - cd webpack-vanilla && npm run e2e && cd ..
