dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - cd smart-webgui && npm install && cd ..
script:
  - cd smart-webgui && npm run lint && cd ..
  - cd smart-webgui && npm run test-once && cd .. 
  - cd smart-webgui && npm run e2e && cd ..
