dist: trusty
sudo: required
language: node_js
node_js:
- '6'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_9f0430de08d1_key -iv $encrypted_9f0430de08d1_iv
  -in ghpages_ecdsa_sacgui.enc -out ghpages_ecdsa_sacgui -d
install:
- npm install
script:
- npm run tslint
- npm run webpack-validate:dev
- npm run webpack-validate:test
- npm run test
- npm run webdriver:update
- npm run build
  # - npm run e2e:ci
after_success:
- chmod 600 ghpages_ecdsa_sacgui && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacgui
- git remote -v
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run build && sh -c $TRAVIS_BUILD_DIR/docker-preps.sh

deploy:
  provider: gcs
  access_key_id: GOOGZDYY4PCU7QXHJ5GS
  secret_access_key:
    secure: DuqJ8mkk+Hcc5H6OGf4Hb9EpehcA0MkawC9ENJPfH4hRdN0wVBr+3cCMY4WfzmZrmpcOUdv2lga+JltVfwLsBoFqxaiN0U3CGGg1N91Lzg3y/3nHfoaYFmZSK7lbOrAfqX7unKCpmzZ86hGFoAMCQhOvx/I3jcCaKZ4ZjWGuN93ragiZzbFQ/9x2s0aRAkUIdc/JVEpPZVCDIhAjd0WrHPZk8zryN6Iq/02xEdMSJFHrHPxSUPcdhPGvOGNG/jht6/HDRmGNzOz22vHLN8vYaTPSBdhv5H+V5NJ5ga23es3nemQu1uEn1b+U++CGfjkJrsN+bY6+XlVQ/Q1wtfh9QTwWAJOukrwQgJzZeLIIxupM+BaQ7VCQzBma/jmLHbxcU169/RBo+YlloNCBY/YcTVRqzIxXpN9tbK5SRhavSqq/t49AYpBL01tKyM+d8uNngz5my1BmF4+zaeZE7TZ/shTxd/8ngDso0L945NswSO+zXS/IJVTK7QuRSidPA9d274bkliWDke0sfSR6qimleru/TNTAO94LWBSP3sPBa9n2X9HFsD/kHC3pDg3ziRG52BMP283qK3EiJI3ucPsbYusEgVYEJniqcUdFmz218V4eufrN1norSTbLfuE6akVH1DOpthPJi1ARPpLMFNzhM0nG/9ET70a/eDuTXvhJ0j4=
  bucket: smart-deploy-artefacts
  upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER"
  local-dir: config/docker/
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
  - allixender@googlemail.com
  webhooks:
    urls:
    - https://admin.smart-project.info/travis/notification
    on_success: always
    on_failure: never
    on_start: never
