dist: trusty
sudo: required
language: node_js
node_js:
- "7"
python:
# - "2.7"
- "3.4"
os:
- linux

cache:
  directories:
    - travis_phantomjs

# https://www.ubuntuupdates.org/ppa/google_chrome?dist=stable
# https://docs.travis-ci.com/user/installing-dependencies#Adding-APT-Sources
# https://docs.travis-ci.com/user/firefox/
addons:
  firefox: "latest"
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      key_url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    packages:
    - google-chrome-stable
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=/usr/bin/google-chrome-stable
  # - CHROME_BIN=chromium-browser
  - PHANTOMJS_BIN=$HOME/node_modules/phantomjs-prebuilt/bin/phantomjs
before_script:
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_9f0430de08d1_key -iv $encrypted_9f0430de08d1_iv
  -in ghpages_ecdsa_sacgui.enc -out ghpages_ecdsa_sacgui -d

- npm i -g npm@3
install:
- npm install
# - pip install --user git+https://github.com/Syntaf/travis-sphinx.git
- pip install -q --user Sphinx sphinx_rtd_theme
- export PATH=$HOME/.local/bin:$PATH
# - node node_modules/protractor/bin/webdriver-manager update
- npm run webdriver:update
# Immune to logouts, but not VM deprovisions!
- nohup bash -c "webdriver-manager start 2>&1 &"
script:
- cp config/internal/.env.travis .env
- npm run stat
- npm run tslint
- npm test -- --ci && cp -r coverage _coverage
# jit build
- npm run e2e:ci:jit
# aot build
# AK 13/07/2017
- npm run e2e:ci
# shpinx docs build
- sphinx-build --version
- sphinx-build -b html src/docs/source sphinx-build
- sh -c $TRAVIS_BUILD_DIR/ghdash-preps.sh

after_success:
- chmod 600 ghpages_ecdsa_sacgui && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacgui

- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run gh-pages-push
# AK 13/07/2017
# - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run clean && npm run build:jit && sphinx-build -b html src/docs/source sphinx-build && sh -c $TRAVIS_BUILD_DIR/docker-preps.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run clean && npm run build && sphinx-build -b html src/docs/source sphinx-build && sh -c $TRAVIS_BUILD_DIR/docker-preps.sh

deploy:
  provider: gcs
  access_key_id: GOOGZDYY4PCU7QXHJ5GS
  secret_access_key:
    secure: DuqJ8mkk+Hcc5H6OGf4Hb9EpehcA0MkawC9ENJPfH4hRdN0wVBr+3cCMY4WfzmZrmpcOUdv2lga+JltVfwLsBoFqxaiN0U3CGGg1N91Lzg3y/3nHfoaYFmZSK7lbOrAfqX7unKCpmzZ86hGFoAMCQhOvx/I3jcCaKZ4ZjWGuN93ragiZzbFQ/9x2s0aRAkUIdc/JVEpPZVCDIhAjd0WrHPZk8zryN6Iq/02xEdMSJFHrHPxSUPcdhPGvOGNG/jht6/HDRmGNzOz22vHLN8vYaTPSBdhv5H+V5NJ5ga23es3nemQu1uEn1b+U++CGfjkJrsN+bY6+XlVQ/Q1wtfh9QTwWAJOukrwQgJzZeLIIxupM+BaQ7VCQzBma/jmLHbxcU169/RBo+YlloNCBY/YcTVRqzIxXpN9tbK5SRhavSqq/t49AYpBL01tKyM+d8uNngz5my1BmF4+zaeZE7TZ/shTxd/8ngDso0L945NswSO+zXS/IJVTK7QuRSidPA9d274bkliWDke0sfSR6qimleru/TNTAO94LWBSP3sPBa9n2X9HFsD/kHC3pDg3ziRG52BMP283qK3EiJI3ucPsbYusEgVYEJniqcUdFmz218V4eufrN1norSTbLfuE6akVH1DOpthPJi1ARPpLMFNzhM0nG/9ET70a/eDuTXvhJ0j4=
  bucket: smart-deploy-artefacts
  upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER"
  local-dir: config/docker/
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
  - allixender@gmail.com
  - grmpfhmbl@gmail.com
  webhooks:
    urls:
    - https://admin.smart-project.info/travis/notification
    on_success: always
    on_failure: never
    on_start: never
