dist: trusty
sudo: required
language: node_js
node_js:
- '6'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_9f0430de08d1_key -iv $encrypted_9f0430de08d1_iv
  -in ghpages_ecdsa_sacgui.enc -out ghpages_ecdsa_sacgui -d
install:
- npm install
script:
- npm run tslint
- npm run webpack-validate:dev
- npm run webpack-validate:test
- npm run test
- npm run webdriver:update
- npm run e2e:ci
after_success:
- chmod 600 ghpages_ecdsa_sacgui && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacgui
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && echo "could push now"
notifications:
  email:
  - allixender@googlemail.com
  webhooks:
    urls:
    - http://admin.smart-project.info/travis/notification
    on_success: always
    on_failure: never
    on_start: never
