apiVersion: v1
kind: Service
metadata:
  annotations:
    notes: "Web Smart Webgui App Service Endpoint"
  labels:
    app: websmartdev
    environment: development
  name: websmartdev
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: websmartdev
    environment: development
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    software: "websmartdev nginx web server with webpack export"
    notes: "TODO test different htdocs deployment options"
  labels:
    app: websmartdev
    environment: development
  name: websmartdev
  namespace: default
spec:
  replicas: 1
  selector:
    app: websmartdev
    environment: development
  template:
    metadata:
      annotations:
        software: "websmartdev nginx web server with webpack export"
        notes: "TODO test different htdocs deployment options"
      labels:
        app: websmartdev
        environment: development
    spec:
      containers:
      - image: eu.gcr.io/dynamic-cove-129211/websmartdev:0.6
        imagePullPolicy: IfNotPresent
        name: websmartdev
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /etc/nginx/secrets
          name: htpasswd-smart
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: htpasswd-smart
        secret:
          secretName: htpasswd-smart
