apiVersion: v1
kind: Service
metadata:
  annotations:
    notes: "Web Smart Admin App Service Endpoint"
  labels:
    app: websmartdev
    environment: development
  name: websmartdev
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: websmartdev
    environment: development
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    software: "websmartdev web server"
    notes: "TODO test different volume variant with some of them read-only"
  labels:
    app: websmartdev
    environment: development
  name: websmartdev
  namespace: default
spec:
  replicas: 1
  selector:
    app: websmartdev
    environment: development
  template:
    metadata:
      annotations:
        software: "websmartdev web server"
        notes: "TODO test different volume variant with some of them read-only"
      labels:
        app: websmartdev
        environment: development
    spec:
      containers:
      - image: gcr.io/$PROJECT/smart-portal-webgui:$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        name: websmartdev
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /etc/nginx/secrets
          name: htpasswd
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: htpasswd
        secret:
          secretName: htpasswd
