dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
# before_install:
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
install:
  - npm install
script:
  - npm run lint
  - npm run test-once
  - npm run e2e
  - npm test
