export * from './search.component'
export * from './result-detail.component'
export * from './result'
export * from './result.service'
export * from './featureOriginFilter.pipe'
export * from './result-detail-modal.component'
// export * from './mock-results'
